export const productsData = [
  {
    category: "Mobiles",
    products: [
      {
        id: 1,
        brand: "Apple",
        model: "iPhone 14",
        price: 999,
        color: "Red",
        storage: "128GB",
        camera: "12MP",
        battery: "3279mAh",
      },
      {
        id: 2,
        brand: "Apple",
        model: "iPhone 14 Pro",
        price: 1099,
        color: "Blue",
        storage: "256GB",
        camera: "48MP",
        battery: "3200mAh",
      },
      {
        id: 3,
        brand: "Samsung",
        model: "Galaxy S22",
        price: 799,
        color: "Green",
        storage: "256GB",
        camera: "50MP",
        battery: "3700mAh",
      },
      {
        id: 4,
        brand: "Samsung",
        model: "Galaxy A52",
        price: 499,
        color: "Black",
        storage: "128GB",
        camera: "64MP",
        battery: "4500mAh",
      },
      {
        id: 5,
        brand: "Google",
        model: "Pixel 7",
        price: 599,
        color: "Yellow",
        storage: "128GB",
        camera: "50MP",
        battery: "4355mAh",
      },
      {
        id: 6,
        brand: "Google",
        model: "Pixel 6a",
        price: 449,
        color: "Red",
        storage: "128GB",
        camera: "12.2MP",
        battery: "4410mAh",
      },
      {
        id: 7,
        brand: "OnePlus",
        model: "9 Pro",
        price: 969,
        color: "Blue",
        storage: "256GB",
        camera: "48MP",
        battery: "4500mAh",
      },
      {
        id: 8,
        brand: "OnePlus",
        model: "Nord 2",
        price: 399,
        color: "Green",
        storage: "128GB",
        camera: "50MP",
        battery: "4500mAh",
      },
      {
        id: 9,
        brand: "Xiaomi",
        model: "Mi 11",
        price: 749,
        color: "Black",
        storage: "256GB",
        camera: "108MP",
        battery: "4600mAh",
      },
      {
        id: 10,
        brand: "Xiaomi",
        model: "Redmi Note 11",
        price: 199,
        color: "Yellow",
        storage: "64GB",
        camera: "50MP",
        battery: "5000mAh",
      },
      {
        id: 11,
        brand: "Sony",
        model: "Xperia 1 III",
        price: 1299,
        color: "Red",
        storage: "256GB",
        camera: "12MP",
        battery: "4500mAh",
      },
      {
        id: 12,
        brand: "Sony",
        model: "Xperia 5 III",
        price: 999,
        color: "Blue",
        storage: "128GB",
        camera: "12MP",
        battery: "4500mAh",
      },
      {
        id: 13,
        brand: "Nokia",
        model: "G50",
        price: 299,
        color: "Green",
        storage: "128GB",
        camera: "48MP",
        battery: "4470mAh",
      },
      {
        id: 14,
        brand: "Nokia",
        model: "X20",
        price: 399,
        color: "Black",
        storage: "128GB",
        camera: "64MP",
        battery: "4470mAh",
      },
      {
        id: 15,
        brand: "Oppo",
        model: "Find X3 Pro",
        price: 1149,
        color: "Yellow",
        storage: "256GB",
        camera: "50MP",
        battery: "4500mAh",
      },
      {
        id: 16,
        brand: "Oppo",
        model: "A74",
        price: 299,
        color: "Red",
        storage: "128GB",
        camera: "48MP",
        battery: "5000mAh",
      },
      {
        id: 17,
        brand: "Huawei",
        model: "P40 Pro",
        price: 999,
        color: "Blue",
        storage: "256GB",
        camera: "50MP",
        battery: "4200mAh",
      },
      {
        id: 18,
        brand: "Huawei",
        model: "Nova 9",
        price: 499,
        color: "Green",
        storage: "128GB",
        camera: "50MP",
        battery: "4300mAh",
      },
      {
        id: 19,
        brand: "Motorola",
        model: "Edge 20",
        price: 499,
        color: "Black",
        storage: "128GB",
        camera: "108MP",
        battery: "4000mAh",
      },
      {
        id: 20,
        brand: "Realme",
        model: "GT Master Edition",
        price: 399,
        color: "Yellow",
        storage: "128GB",
        camera: "64MP",
        battery: "4300mAh",
      },
    ],
  },
  {
    category: "Books",
    products: [
      {
        id: 1001,
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        price: 10.99,
        genre: "Classic",
        pages: 180,
        publisher: "Charles Scribner's Sons",
      },
      {
        id: 1002,
        title: "1984",
        author: "George Orwell",
        price: 9.99,
        genre: "Dystopian",
        pages: 328,
        publisher: "Secker & Warburg",
      },
      {
        id: 1003,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        price: 14.99,
        genre: "Fiction",
        pages: 281,
        publisher: "J.B. Lippincott & Co.",
      },
      {
        id: 1004,
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        price: 11.99,
        genre: "Fiction",
        pages: 277,
        publisher: "Little, Brown and Company",
      },
      {
        id: 1005,
        title: "Pride and Prejudice",
        author: "Jane Austen",
        price: 12.99,
        genre: "Romance",
        pages: 279,
        publisher: "T. Egerton",
      },
      {
        id: 1006,
        title: "The Hobbit",
        author: "J.R.R. Tolkien",
        price: 15.99,
        genre: "Fantasy",
        pages: 310,
        publisher: "George Allen & Unwin",
      },
      {
        id: 1007,
        title: "Moby Dick",
        author: "Herman Melville",
        price: 13.99,
        genre: "Adventure",
        pages: 585,
        publisher: "Harper & Brothers",
      },
      {
        id: 1008,
        title: "War and Peace",
        author: "Leo Tolstoy",
        price: 19.99,
        genre: "Historical Fiction",
        pages: 1225,
        publisher: "The Russian Messenger",
      },
      {
        id: 1009,
        title: "The Alchemist",
        author: "Paulo Coelho",
        price: 9.99,
        genre: "Fiction",
        pages: 208,
        publisher: "HarperCollins",
      },
      {
        id: 1010,
        title: "The Book Thief",
        author: "Markus Zusak",
        price: 14.99,
        genre: "Historical Fiction",
        pages: 552,
        publisher: "Knopf",
      },
      {
        id: 1011,
        title: "The Fault in Our Stars",
        author: "John Green",
        price: 12.99,
        genre: "Young Adult",
        pages: 313,
        publisher: "Dutton Books",
      },
      {
        id: 1012,
        title: "Brave New World",
        author: "Aldous Huxley",
        price: 11.99,
        genre: "Dystopian",
        pages: 268,
        publisher: "Chatto & Windus",
      },
      {
        id: 1013,
        title: "The Chronicles of Narnia",
        author: "C.S. Lewis",
        price: 29.99,
        genre: "Fantasy",
        pages: 768,
        publisher: "Geoffrey Bles",
      },
    ],
  },
  {
    category: "Appliances",
    products: [
      {
        id: 21,
        brand: "Samsung",
        model: "Smart Fridge",
        price: 1499,
        color: "Stainless Steel",
        capacity: "27 cu ft",
        energyRating: "Energy Star",
        features: ["Wi-Fi Connectivity", "Touch Screen", "Ice Maker"],
      },
      {
        id: 22,
        brand: "LG",
        model: "Washer Dryer Combo",
        price: 1199,
        color: "White",
        capacity: "4.5 cu ft",
        energyRating: "Energy Star",
        features: ["Smart Diagnosis", "Steam Technology"],
      },
      {
        id: 23,
        brand: "Bosch",
        model: "Built-In Dishwasher",
        price: 899,
        color: "Black",
        capacity: "16 Place Settings",
        energyRating: "Energy Star",
        features: ["Quiet Operation", "Auto Programs"],
      },
      {
        id: 24,
        brand: "Dyson",
        model: "V11 Torque Drive Vacuum",
        price: 599,
        color: "Purple",
        type: "Cordless Vacuum",
        batteryLife: "60 minutes",
        features: ["Smart Sensor", "High Torque Cleaner Head"],
      },
      {
        id: 25,
        brand: "KitchenAid",
        model: "Stand Mixer",
        price: 379,
        color: "Empire Red",
        capacity: "5 qt",
        features: ["10 Speed Settings", "Tilt-Head Design"],
      },
      {
        id: 26,
        brand: "Whirlpool",
        model: "Top Load Washer",
        price: 749,
        color: "White",
        capacity: "4.3 cu ft",
        energyRating: "Energy Star",
        features: ["Adaptive Wash Technology", "Agitator"],
      },
      {
        id: 27,
        brand: "Frigidaire",
        model: "Air Conditioner",
        price: 299,
        color: "White",
        coolingCapacity: "8000 BTU",
        energyRating: "Energy Star",
        features: ["Remote Control", "Energy Saver Mode"],
      },
      {
        id: 28,
        brand: "Instant Pot",
        model: "Duo 7-in-1",
        price: 89,
        color: "Stainless Steel",
        capacity: "6 qt",
        features: ["Pressure Cook", "Slow Cook", "Rice Cook"],
      },
      {
        id: 29,
        brand: "Nespresso",
        model: "Vertuo Coffee Maker",
        price: 199,
        color: "Black",
        features: ["One-Touch Brewing", "Multiple Cup Sizes"],
      },
      {
        id: 30,
        brand: "Cuisinart",
        model: "Food Processor",
        price: 149,
        color: "White",
        capacity: "14 cup",
        features: ["Slicing Disc", "Dough Blade"],
      },
      {
        id: 31,
        brand: "Sony",
        model: "Smart TV 55 inch",
        price: 999,
        color: "Black",
        features: ["4K UHD", "HDR", "Voice Control"],
      },
      {
        id: 32,
        brand: "Bissell",
        model: "Steam Mop",
        price: 79,
        color: "Blue",
        features: ["Sanitizes Floors", "Easy to Use"],
      },
      {
        id: 33,
        brand: "Philips",
        model: "Air Fryer",
        price: 199,
        color: "Black",
        features: ["Rapid Air Technology", "Recipe Book Included"],
      },
      {
        id: 34,
        brand: "Panasonic",
        model: "Microwave Oven",
        price: 149,
        color: "Silver",
        features: ["Inverter Technology", "Sensor Cooking"],
      },
      {
        id: 35,
        brand: "Shark",
        model: "Robot Vacuum",
        price: 299,
        color: "Black",
        features: ["Self-Empty Base", "Smart Navigation"],
      },
      {
        id: 36,
        brand: "GE",
        model: "Electric Range",
        price: 899,
        color: "Stainless Steel",
        features: ["Convection Oven", "Self-Cleaning"],
      },
      {
        id: 37,
        brand: "Tefal",
        model: "Crispy Fryer",
        price: 129,
        color: "Red",
        features: ["Oil-Free Cooking", "Dishwasher Safe"],
      },
      {
        id: 38,
        brand: "Miele",
        model: "Vacuum Cleaner",
        price: 599,
        color: "Yellow",
        features: ["Bagged Canister", "Active AirClean Filter"],
      },
      {
        id: 39,
        brand: "SodaStream",
        model: "Fizzi Sparkling Water Maker",
        price: 89,
        color: "Black",
        features: ["Reusable Carbonating Bottle", "Quick & Easy"],
      },
      {
        id: 40,
        brand: "Ecovacs",
        model: "Deebot Ozmo T8",
        price: 499,
        color: "Black",
        features: ["Vacuum and Mop", "Smart App Control"],
      },
    ],
  },
];
