export const productData = [
  {
    id: 1,
    brand: "Apple",
    model: "iPhone 14",
    price: 999,
    color: "Red",
    storage: "128GB",
    camera: "12MP",
    battery: "3279mAh",
  },
  {
    id: 2,
    brand: "Apple",
    model: "iPhone 14 Pro",
    price: 1099,
    color: "Blue",
    storage: "256GB",
    camera: "48MP",
    battery: "3200mAh",
  },
  {
    id: 3,
    brand: "Samsung",
    model: "Galaxy S22",
    price: 799,
    color: "Green",
    storage: "256GB",
    camera: "50MP",
    battery: "3700mAh",
  },
  {
    id: 4,
    brand: "Samsung",
    model: "Galaxy A52",
    price: 499,
    color: "Black",
    storage: "128GB",
    camera: "64MP",
    battery: "4500mAh",
  },
  {
    id: 5,
    brand: "Google",
    model: "Pixel 7",
    price: 599,
    color: "Yellow",
    storage: "128GB",
    camera: "50MP",
    battery: "4355mAh",
  },
  {
    id: 6,
    brand: "Google",
    model: "Pixel 6a",
    price: 449,
    color: "Red",
    storage: "128GB",
    camera: "12.2MP",
    battery: "4410mAh",
  },
  {
    id: 7,
    brand: "OnePlus",
    model: "9 Pro",
    price: 969,
    color: "Blue",
    storage: "256GB",
    camera: "48MP",
    battery: "4500mAh",
  },
  {
    id: 8,
    brand: "OnePlus",
    model: "Nord 2",
    price: 399,
    color: "Green",
    storage: "128GB",
    camera: "50MP",
    battery: "4500mAh",
  },
  {
    id: 9,
    brand: "Xiaomi",
    model: "Mi 11",
    price: 749,
    color: "Black",
    storage: "256GB",
    camera: "108MP",
    battery: "4600mAh",
  },
  {
    id: 10,
    brand: "Xiaomi",
    model: "Redmi Note 11",
    price: 199,
    color: "Yellow",
    storage: "64GB",
    camera: "50MP",
    battery: "5000mAh",
  },
  {
    id: 11,
    brand: "Sony",
    model: "Xperia 1 III",
    price: 1299,
    color: "Red",
    storage: "256GB",
    camera: "12MP",
    battery: "4500mAh",
  },
  {
    id: 12,
    brand: "Sony",
    model: "Xperia 5 III",
    price: 999,
    color: "Blue",
    storage: "128GB",
    camera: "12MP",
    battery: "4500mAh",
  },
  {
    id: 13,
    brand: "Nokia",
    model: "G50",
    price: 299,
    color: "Green",
    storage: "128GB",
    camera: "48MP",
    battery: "4470mAh",
  },
  {
    id: 14,
    brand: "Nokia",
    model: "X20",
    price: 399,
    color: "Black",
    storage: "128GB",
    camera: "64MP",
    battery: "4470mAh",
  },
  {
    id: 15,
    brand: "Oppo",
    model: "Find X3 Pro",
    price: 1149,
    color: "Yellow",
    storage: "256GB",
    camera: "50MP",
    battery: "4500mAh",
  },
  {
    id: 16,
    brand: "Oppo",
    model: "A74",
    price: 299,
    color: "Red",
    storage: "128GB",
    camera: "48MP",
    battery: "5000mAh",
  },
  {
    id: 17,
    brand: "Huawei",
    model: "P40 Pro",
    price: 999,
    color: "Blue",
    storage: "256GB",
    camera: "50MP",
    battery: "4200mAh",
  },
  {
    id: 18,
    brand: "Huawei",
    model: "Nova 9",
    price: 499,
    color: "Green",
    storage: "128GB",
    camera: "50MP",
    battery: "4300mAh",
  },
  {
    id: 19,
    brand: "Motorola",
    model: "Edge 20",
    price: 499,
    color: "Black",
    storage: "128GB",
    camera: "108MP",
    battery: "4000mAh",
  },
  {
    id: 20,
    brand: "Realme",
    model: "GT Master Edition",
    price: 399,
    color: "Yellow",
    storage: "128GB",
    camera: "64MP",
    battery: "4300mAh",
  },
  {
    id: 21,
    brand: "Asus",
    model: "Zenfone 8",
    price: 699,
    color: "Red",
    storage: "128GB",
    camera: "64MP",
    battery: "4000mAh",
  },
  {
    id: 22,
    brand: "Vivo",
    model: "X70 Pro",
    price: 799,
    color: "Blue",
    storage: "256GB",
    camera: "50MP",
    battery: "4450mAh",
  },
  {
    id: 23,
    brand: "ZTE",
    model: "Axon 20",
    price: 499,
    color: "Green",
    storage: "128GB",
    camera: "64MP",
    battery: "4220mAh",
  },
  {
    id: 24,
    brand: "Poco",
    model: "F3",
    price: 349,
    color: "Black",
    storage: "256GB",
    camera: "48MP",
    battery: "4520mAh",
  },
  {
    id: 25,
    brand: "LG",
    model: "Wing",
    price: 999,
    color: "Yellow",
    storage: "256GB",
    camera: "64MP",
    battery: "4000mAh",
  },
  {
    id: 26,
    brand: "TCL",
    model: "10 Pro",
    price: 449,
    color: "Red",
    storage: "128GB",
    camera: "64MP",
    battery: "4500mAh",
  },
  {
    id: 27,
    brand: "HTC",
    model: "Desire 20 Pro",
    price: 329,
    color: "Blue",
    storage: "128GB",
    camera: "48MP",
    battery: "5000mAh",
  },
  {
    id: 28,
    brand: "Honor",
    model: "X40 GT",
    price: 399,
    color: "Green",
    storage: "256GB",
    camera: "50MP",
    battery: "4800mAh",
  },
  {
    id: 29,
    brand: "Apple",
    model: "iPhone 13",
    price: 799,
    color: "Black",
    storage: "128GB",
    camera: "12MP",
    battery: "3240mAh",
  },
  {
    id: 30,
    brand: "Samsung",
    model: "Galaxy Z Flip3",
    price: 999,
    color: "Yellow",
    storage: "128GB",
    camera: "12MP",
    battery: "3300mAh",
  },
  {
    id: 31,
    brand: "Google",
    model: "Pixel 5",
    price: 699,
    color: "Red",
    storage: "128GB",
    camera: "16MP",
    battery: "4080mAh",
  },
  {
    id: 32,
    brand: "OnePlus",
    model: "Nord CE 5G",
    price: 399,
    color: "Blue",
    storage: "128GB",
    camera: "64MP",
    battery: "4500mAh",
  },
  {
    id: 33,
    brand: "Xiaomi",
    model: "Poco X3 Pro",
    price: 299,
    color: "Green",
    storage: "128GB",
    camera: "48MP",
    battery: "5160mAh",
  },
  {
    id: 34,
    brand: "Sony",
    model: "Xperia 10 III",
    price: 399,
    color: "Black",
    storage: "128GB",
    camera: "12MP",
    battery: "4500mAh",
  },
  {
    id: 35,
    brand: "Nokia",
    model: "C30",
    price: 149,
    color: "Yellow",
    storage: "64GB",
    camera: "13MP",
    battery: "6000mAh",
  },
  {
    id: 36,
    brand: "Oppo",
    model: "Reno 6",
    price: 599,
    color: "Red",
    storage: "128GB",
    camera: "64MP",
    battery: "4300mAh",
  },
  {
    id: 37,
    brand: "Huawei",
    model: "Mate 40 Pro",
    price: 1199,
    color: "Blue",
    storage: "256GB",
    camera: "50MP",
    battery: "4400mAh",
  },
];
